export const RESET_LIFE = 'RESET_LIFE';
export const REQUEST_PREVIOUS_STEP = 'REQUEST_PREVIOUS_STEP';
export const RECEIVE_PREVIOUS_STEP = 'RECEIVE_PREVIOUS_STEP';
export const REQUEST_LAST_STEP = 'REQUEST_LAST_STEP';
export const RESTORE_LIFE = 'RESTORE_LIFE';
export const READ_ONLY_ERROR = 'READ_ONLY_ERROR';
